### ISSUE TITLE
downloading odenet fails - handle 302 redirects

### ISSUE THREAD

**Issue by Laubeee** [goodmami/wn#211]
**Describe the bug**
odenet:1.4 cannot be downloaded due to 302 redirect. The redirect is valid and using the URL in a browser works.

**To Reproduce**
```pycon
>>> wn.download("odenet:1.4")
Download (0 bytes) Requesting
Traceback (most recent call last):
  File "C:\Users\Silvan\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Projects\at_SC\venv310\lib\site-packages\wn\_download.py", line 66, in download
    path = _download(urls, progress)
  File "C:\Projects\at_SC\venv310\lib\site-packages\wn\_download.py", line 102, in _download
    response.raise_for_status()
  File "C:\Projects\at_SC\venv310\lib\site-packages\httpx\_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '302 Found' for url 'https://github.com/hdaSprachtechnologie/odenet/releases/download/v1.4/odenet-1.4.tar.xz'
Redirect location: 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/92867134/4651e613-d114-4052-9d0d-681b2062e5aa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241031%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241031T124254Z&X-Amz-Expires=300&X-Amz-Signature=43b51cd7e51674ed3a7940432a8686dbfa80c9b3f738982937e9ddef5494fc9d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dodenet-1.4.tar.xz&response-content-type=application%2Foctet-stream'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302
```

**Expected behavior**
that downloading of listed projects works

**Environment**
python 3.10.8
wn 0.10.0

**Additional context**
perhaps a simple `follow_redirects=True` in https://github.com/goodmami/wn/blob/8ea1e2764e4da479f0fa7617b0470feda628748c/wn/_download.py#L101 would already solve the problem.

**Comment by goodmami** [comment]
Thanks! I'm pretty sure this is because I recently switched from `requests` to `httpx`, which [does not follow redirects by default](https://www.python-httpx.org/compatibility/). Your proposed fix sounds good.

**Comment by Laubeee** [comment]
I see. If there are other places where this option should be enabled feel free to enhance the PR before merging
