### ISSUE TITLE
httpx.HTTPStatusError: Redirect Response '302 Found'

### ISSUE THREAD

**Issue by klebster2** [goodmami/wn#223]
**Describe the bug**
I was unable to download the french wn: https://github.com/omwn/omw-data/releases/download/v1.4/omw-fr-1.4.tar.xz
Apparently there are a couple of redirects

:warning: If this is a question about Wn or how to use it, please create a [discussion](https://github.com/goodmami/wn/discussions) instead of an issue.

**To Reproduce**
```console
$ python -m wn download omw-fr:1.4
Download (0 bytes) Requesting
Traceback (most recent call last):
  File ".../miniconda3/envs/pynvim/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../miniconda3/envs/pynvim/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../miniconda3/envs/pynvim/lib/python3.9/site-packages/wn/__main__.py", line 176, in <module>
    args.func(args)
  File ".../miniconda3/envs/pynvim/lib/python3.9/site-packages/wn/__main__.py", line 18, in _download
    wn.download(target, add=args.add)
  File ".../miniconda3/envs/pynvim/lib/python3.9/site-packages/wn/_download.py", line 66, in download
    path = _download(urls, progress)
  File ".../miniconda3/envs/pynvim/lib/python3.9/site-packages/wn/_download.py", line 102, in _download
    response.raise_for_status()
  File ".../miniconda3/envs/pynvim/lib/python3.9/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '302 Found' for url 'https://github.com/omwn/omw-data/releases/download/v1.4/omw-fr-1.4.tar.xz'
Redirect location: 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/310510347/cd844b56-8687-4cb7-9e82-19d4729c31ea?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241110%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241110T150354Z&X-Amz-Expires=300&X-Amz-Signature=192ca8d10a075bbf254a7ace8c3d426bd0b5cf7f3e7c0b4812aa87721fed0213&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Domw-fr-1.4.tar.xz&response-content-type=application%2Foctet-stream'
```

**Expected behavior**
The resource downloads as specified in the documentation

**Environment**
Using:
python=3.10.14
wn==0.10.0
httpx==0.27.2

```console
python --version
python -m wn --version
python -m wn lexicons
```

**Additional context**
I found that adding the argument allowing for redirects in the httpx.stream call [here](
https://github.com/goodmami/wn/blob/33d5bdb82e580eb04f4246158efdbeacb6eeb14f/wn/_download.py#L102C1-L102C64
) corrected the issue.

E.g. changing:
```python
with httpx.stream("GET", url, timeout=TIMEOUT):
    ...
```
To
```python
with httpx.stream("GET", url, timeout=TIMEOUT, follow_redirects=True):
    ...
```

**Comment by goodmami** [comment]
Thanks for the report! This was already reported (https://github.com/goodmami/wn/issues/211) and fixed. Please install [Wn v0.10.1](https://github.com/goodmami/wn/releases/tag/v0.10.1).

**Comment by klebster2** [comment]
Thanks, working
